H3=CoxeterGroup(['H',3])

l1=[31,231,3231,23231,123231]
l2=[312,2312,32312,232312,1232312]
l3=[3123,23123,323123,2323123,12323123]
l4=[31232,231232,3231232,23231232,123231232]
l5=[312321,2312321,32312321,232312321,1232312321]

def decompose(w,s,t):
    """ Return the "parabolic * minimal representative" decomposition of w with
    respect to the parabolic subgroup generated by s and t."""
    w = H3.from_reduced_word(w)
    coset_rep = w.coset_representative([s,t],side='left')
    parabolic_rep = w *  coset_rep.inverse()
    parabolic = parabolic_rep.reduced_word()
    rep = coset_rep.reduced_word()
    return parabolic, rep

def fc_cardinality(n):
    return binomial(2*n+2,n+1)-2**(n+2)+n+3

def subregular_cardinality(n):
    return 2*n*n+1

def fcnsb(n):
    return fc_cardinality(n)-subregular_cardinality(n)
